# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheBestsMovies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#    pod 'RxSwift', '~> 5'
#    pod 'RxCocoa', '~> 5'

  # Pods for TheBestsMovies

  target 'TheBestsMoviesTests' do
    inherit! :search_paths
#    pod 'RxBlocking', '~> 5'
#    pod 'RxTest', '~> 5'
  end

end
